on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *"  # Runs at midnight (0:00) every 3rd day

jobs:
  run_ruby_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
      - name: Install Bundler
        run: |
          gem list bundle
      - name: Bundle install dependencies
        run: bundle install  
      - name: Set environment variable (securely)
        run: |
          echo "::group::"
          echo "Setting GITHUB_PERSONAL_ACCESS_TOKEN..."
          echo "GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUBPA }}" >> $GITHUB_ENV  # Store token securely
          echo "::endgroup::"
      - name: Update contributors list
        run: ruby main.rb
      - name: Commit and push new contributors.json
        run: |
          git config --global user.email "github_actions@mail.com"
          git config --global user.name "github actions"
          git add json/contributors.json
          git commit -m "fix: update contributors list at json/contributors.json"
